[package]
name = "geng_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geng = { git = "https://github.com/geng-engine/geng" }
serde = { version = "1", features = ["derive"] }
