[package]
name = "geng_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geng = "0.15"
image = "0.24.6"
serde = { version = "1", features = ["derive"] }
